name: "Xfinity Internet Usage"
description: "Get Xfinity Internet Usage Data"
url: "https://github.com/spiyderz/hassio-xfinity-usage_fork"
version: "0.0.12.8"
image: "ghcr.io/thor0215/hassio-xfinity-usage-{arch}"
slug: "xfinity-usage"
init: false
arch:
  - aarch64
  - amd64
startup: application
boot: auto
homeassistant_api: true
hassio_api: true
hassio_role: manager
panel_icon: mdi:network
init: false
map:
  - addon_config:rw
backup_exclude:
  - "profile*"
services:
  - mqtt:want

options:
  xfinity_username:
  xfinity_password:
  page_timeout: 60
  polling_rate: 900
  log_level: info
  mqtt_enabled: false
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_username: addons

schema:
  xfinity_username: str
  xfinity_password: password
  page_timeout: int(15,)?
  polling_rate: int(30,)?
  log_level: list(info|debug|debug_support)?
  mqtt_enabled: bool?
  mqtt_host: str?
  mqtt_port: port?
  mqtt_username: str?
  mqtt_password: password?
